{% set name = "m2r2" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cac62204ed10119cdc98311cc7fb9f95f6adf07bfb39b1d725f25d56b310ccb

build:
  number: 0
  noarch: python
  entry_points:
    - m2r2 = m2r2:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils
    - mistune
    - python >=3.6

test:
  imports:
    - m2r2
  commands:
    - pip check
    - m2r2 --help
  requires:
    - pip

about:
  home: https://github.com/crossnox/m2r2
  summary: Markdown and reStructuredText in a single file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
