{% set name = "m2r2" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccd95b052dcd1ac7442ecb3111262b2001c10e4119b459c34c93ac7a5c2c7868

build:
  number: 0
  noarch: python
  entry_points:
    - m2r2 = m2r2:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils
    - mistune 0.8.4
    - python >=3.6

test:
  imports:
    - m2r2
  commands:
    - pip check
    - m2r2 --help
  requires:
    - pip

about:
  home: https://github.com/crossnox/m2r2
  summary: Markdown and reStructuredText in a single file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - xylar
